### ISSUE TITLE
pipeline.sh

### ISSUE THREAD

**Issue by ale07alvarez** [funpopgen/veqtl-mapper#1]
Hi,
I am trying to run the pipeline.sh script on my own data but the script is adapted to a different cluster platform and I am having trouble running the analysis.
1. First I did edit the bsub commands to qsub.
2.Second line qsub -o out.veqtl -J"veqtl[1-490]" "veqtl_mapper --bed geuvadis.linc.protein.cov.50PC.bed --vcf Genotypes.individuals_filtered.maf0.05.vcf.gz --genes 29 --job-number \$LSB_JOBINDEX --verbose --perm 10000,4 --out results.veqtl\$LSB_JOBINDEX"
the following **commands are not recognized**:
**-J"veqtl[1-490]"**
qsub: ERROR! invalid option argument "-Jveqtl[1-490]"
and 
**"veqtl_mapper** 
Unable to read script file because of error: error opening veqtl_mapper --bed phenotype.bed --vcf genotype.vcf.gz --genes 29 --job-number $LSB_JOBINDEX --verbo: No such file or directory

from the documentation on:
https://funpopgen.github.io/veqtl-mapper/
the command 
bsub -o out -J"veqtl[1-200]" \
     "veqtl-mapper --bed expression.bed --vcf genotype.vcf.gz --genes 50 \
     --job-number \$LSB_JOBINDEX --out results\$LSB_JOBINDEX"
what software/script is called? veqtl-mapper? ....I downloaded the 
veqtl-mapper-master folder and do not have any scripts named veqtl-mapper.

Can you please provide details on possible solutions to this problem.
Thank you!

**Comment by abrown25** [comment]
The command was written for an LSF cluster to submit 490 jobs at the same time (an array job), you'll have to change it depending on how your cluster type handles array jobs. This means changing the -J"veqtl[1-490]" flag to how your cluster specifies the number of jobs and $LSB_JOBINDEX to how the job index is passed.

For example, for a cluster running under TORQUE, -J"veqtl[1-490]" becomes -t 1-490 and $LSB_JOBINDEX becomes $PBS_ARRAYID so the command becomes:

qsub -t 1-490 "veqtl_mapper --bed geuvadis.linc.protein.cov.50PC.bed --vcf Genotypes.individuals_filtered.maf0.05.vcf.gz --genes 29 --job-number $PBS_ARRAYID --verbose --perm 10000,4 --out results.veqtl$PBS_ARRAYID"

As for the veqtl-mapper program, you can find it here:

https://github.com/funpopgen/veqtl-mapper/releases/tag/1.01

**Comment by ale07alvarez** [comment]
Thank you,
I was able to run the program in the following way:
veqtl-mapper --bed exprs.bed --vcf genotypes.vcf.gz --verbose --perm 10000,4
but have the following output:
335 individuals present in phenotype file.
335 individuals present in genotype file.
**No individuals to analyse.**
