### ISSUE TITLE
use covariates to adjust genotypes

### ISSUE THREAD

**Issue by ale07alvarez** [funpopgen/veqtl-mapper#12]
Hi Andrew,
Does veqtl-mapper have an option for adding a covariate file? If it does not, I think this would make an excellent feature to add since so many studies use genotypes from populations that require such adjustment.

**Comment by abrown25** [comment]
I agree that it would be good functionality to have, and it is on my list of things to do, but I don't know when I'll get round to it. In the meantime, what I did with the geuvadis data was to pre-correct for population by regressing it out first.

**Comment by abrown25** [comment]
This has now been added, along with the ability to control for known eQTLs. It's in the latest release (1.02). The documentation on the website describes the format for the input files and how to use the options.
Best
Andrew
