### ISSUE TITLE
Spearman correlation test - help to understand

### ISSUE THREAD

**Issue by Veliborka** [funpopgen/veqtl-mapper#13]
I am struggling to understand how did you use the Spearman rank correlation test between genotype dosage or between indicator variable for heterozygosity and variance. From what I understood
 Spearman rank correlation test is possible to use when we have paired data. But here we have unpaired genotype groups with different numbers of samples in each group. Could you please explain me which type of formula did you use and how did you construct ranks for genotypes? Or could you please provide me with a paper describing this? I have read a lot of papers but could not find any of such examples. 

Thank you very much

**Comment by abrown25** [comment]
The paired values are each individual genotype paired with that individual's expression phenotype (the expression phenotypes are a distance measure, capturing the difference between actual and expected expression).
Genotypes are just ranked as standard accounting for ties, so in the case of heterozygous effects there are only 2 values an individual can have, depending on whether they are homozygous or heterozygous. 
Beyond the paper that introduced the software the methods are also described for additive variance effects here: https://elifesciences.org/articles/01381
For mapping parent of origin with variance QTL you could look at this: http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1004508

**Comment by Veliborka** [comment]
Ok, I got it. Looking at your source code I finally understood that you used fractional ranking for genotype values. 

Thank you very much for your quick reply,
All the best
