### ISSUE TITLE
PermP | FWER

### ISSUE THREAD

**Issue by ale07alvarez** [funpopgen/veqtl-mapper#4]
Hi
I obtained 
P | **PermP** | **FWER** | BETA
4.20X10-06 | **9.99X10-05** | **9.99X10-05** | 0.000185
the PermP and FWER are identical is this possible?
Thanks!

**Comment by funpopgen** [comment]
Yes, they should be the same for highly significant SNPs as it would mean no more significant result was seen across all permutations and SNPs tested.
