### ISSUE TITLE
normal distribution

### ISSUE THREAD

**Issue by ale07alvarez** [funpopgen/veqtl-mapper#7]
According to the supplementary material:
"data was mapped onto a normal distribution to remove mean-variance effects and outlier driven false positives".
I apologize if this is very naive but what method was used to transform the data to a normal distribution and does the method matter?

**In FastQTL :**there is this additional functionality:
(1) To make the method more robust to outliers in the phenotype
data, FastQTL has an option that allows to **quantile normalize the
phenotype quantifications prior to any analysis. This ensures that
phenotype quantifications are normally distributed with mean 0 and
standard deviation 1**. Quantile normalization is implemented as in
the R/rntransform function of the GenABEL package (Aulchenko
et al., 2007). 
Does veQTL mapper have such a function?
Thanks!

**Comment by abrown25** [comment]
Sorry, the program does not have this function as a built in. You can use GenABEL within R to transform the phenotype before analysis, it is documented here:

http://genabel.org/GenABEL/rntransform.html

**Comment by abrown25** [comment]
I think this is useful functionality to have, if you download the latest version from here:

https://github.com/funpopgen/veqtl-mapper/releases/tag/1.01

then passing the --normal flag will map your data onto a normal distribution.

**Comment by ale07alvarez** [comment]
I have the latest version:
veqtl-mapper --version
veqtl-mapper  -  Variance association mapping for molecular phenotypes version 1.0.1-a59771a
Compiled with Digital Mars D 2.72 at 18:42:24, 23 Jan 2017.

and if I use —normal option:


veqtl-mapper --normal 
Unrecognized option --normal

veqtl-mapper: mapping variance associated loci.

          --bed Phenotype file [last argument].

          --vcf Genotype file.

-o        --out Output file [stdout].

      --verbose Print additional information.

        --genes This specifies the number of genes to be analysed in each job.

   --job-number Split the analysis into a number of smaller runs which can run in parallel on a cluster. This option specifies which of the sub-analyses should be run.

          --het Tests for variance differences in the heterozygous relative to homozygous groups, an indication of parent of origin effects.

         --perm Specify number of permutations, with optional seed. One following number indicates the number of permutations, two comma separated numbers gives the number of permutations and the seed.

       --window The size in base pairs of the cis window around the transcription start site of the gene [1,000,000].

     --noheader Suppress writing of header line.

      --nocheck Do not use the header lines to match genotype and phenotype, assume samples already match.

      --version Display version information.

-h       --help This help information.

for completeness I also have the entire command:
I also tried using the —normal:

veqtl-mapper --bed exprs.bed --vcf tidy.vcf.gz --verbose --perm 10000,4 --normal --out results.veqtl.10000.normal

Unrecognized option —normal




Please help!
Alejandra

**Comment by abrown25** [comment]
That's not the latest version. If you download it from the link running veqtl-mapper --version will give:

veqtl-mapper  -  Variance association mapping for molecular phenotypes version 1.0.1-8192f72
Compiled with Digital Mars D 2.74 at 14:59:06, 11 Oct 2017.
