### ISSUE TITLE
N/A values in the phenotype file

### ISSUE THREAD

**Issue by ale07alvarez** [funpopgen/veqtl-mapper#8]
Hi,
can veqtl-mapper handle N/A values in the expression file(phenotype)
**The output from a file containing N/A values.**
xxx individuals present in phenotype file.
xxx individuals present in genotype file.
Looking for variance effects.
Failed to read gene xxxxx.
No phenotypes read from file.
Please help!
Thanks!

**Comment by ale07alvarez** [comment]
Could you add this functionality to the software?
Thanks.

**Comment by abrown25** [comment]
There are many different ways of handling missing data, depending on how the missingness is generated, the data type and the question being asked (e.g., imputation approaches from genetic data/some metabolites, dropping observations for missing completely at random expression data, etc., etc.).
I don't want to unilaterally enforce a decision as to which approach to take, so I do not currently plan to change the behaviour with missing data (which is right now dropping the phenotype).
The fastQTL approach is to impute the average value of the phenotype for missing data points, you could do this in a preprocessing step if you think it is appropriate for your use case.
