### ISSUE TITLE
Question about Samples file

### ISSUE THREAD

**Issue by VekiJ** [funpopgen/veqtl-mapper#9]
Hello,

I am trying to follow your pipeline and I have a question regarding preprocessing genotype data.

In a command "bcftools view --force-samples -S Samples -Ou", which Samples file did you use?

Thank you very much,
Best regards

**Comment by abrown25** [comment]
I've uploaded the Samples file to here: https://github.com/funpopgen/veqtl-mapper/blob/master/pipeline/Samples and also added a line to pipeline.sh which will generate it automatically from the bed file https://github.com/funpopgen/veqtl-mapper/commit/0c3fcf2982583a440f674c08120e12b4706eb033.

There are 462 individuals in the bed file, with RNA-seq from Geuvadis (this is the list of individuals in the Samples file). Of these, you should find 445 also have DNA-seq.
